
package view;

import DAO.*;
import DAO.LivrosDAO;
import DAO.EmprestimosDAO;
import model.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;
import model.Livros;
import model.Emprestimos;
import java.util.List;

import DAO.LivrosDAO;  
import DAO.EmprestimosDAO;
import DAO.ConfiguracaoDAO;
import controller.RegistroAtividade;
import model.Livros;
import model.Emprestimos;
import java.util.List;
import controller.SistemaLogin;

    
/**
 * Janela principal do gestor do sistema de biblioteca.
 * Permite gerenciar livros, visualizar atividades e configurar taxas.
 */

public class MenuGestor extends javax.swing.JFrame {
    
    /**
     * Construtor que inicializa a interface do gestor.
     * Configura painéis, carrega dados iniciais e define a taxa de empréstimo.
     */
    
    // VARIaVEIS 
  private LivrosDAO livroDAO;
  private EmprestimosDAO emprestimoDAO;
  private ConfiguracaoDAO configDAO;
    private double taxaEmprestimo;
    private String nomeUsuario = "Gestor";
    
public void setNomeUsuario(String nome) {
    this.nomeUsuario = nome;
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuGestor.class.getName());

    /**
     * Creates new form MenuGestor
     */
    public MenuGestor() {
        initComponents();
       // puxa o nome do usuario logado a partir do login 
        String nomeUsuario = Login.usuarioLogadoGlobal;
    this.setTitle("Gestor - " + nomeUsuario);
    
        setLocationRelativeTo(null);
    setResizable(false);
     
       this.livroDAO = new LivrosDAO();
this.emprestimoDAO = new EmprestimosDAO();
this.configDAO = new ConfiguracaoDAO();

    if (livroDAO == null) {
        livroDAO = new LivrosDAO();
    }
        BibliotecaPanel.setVisible(true);
        CadastrarLivrosPanel.setVisible(false);
        AtividadeGestPanel.setVisible(false);
    
    
    // CARREGAR TAXA DO ARQUIVO
    taxaEmprestimo = configDAO.getTaxaEmprestimo();
    txtLivroTaxa.setText(taxaEmprestimo + " MZN");
    
    carregarTabelaLivros();
    carregarAtividadesGestor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        SairLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtPesquisar = new javax.swing.JTextField();
        lupaLabel = new javax.swing.JLabel();
        jP01 = new javax.swing.JPanel();
        BibliotecaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BibliotecaTable = new javax.swing.JTable();
        txtLivroTaxa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CadastrarLivrosPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        AtividadeGestPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(94, 42, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab1.setBackground(new java.awt.Color(94, 42, 43));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab1MouseEntered(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(201, 169, 154));
        jLabel2.setText("Biblioteca");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(29, 29, 29))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(tab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 140, 30));

        tab2.setBackground(new java.awt.Color(94, 42, 43));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab2MouseEntered(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(201, 169, 154));
        jLabel3.setText("Adicionar Livros");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(tab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 140, 30));

        tab3.setBackground(new java.awt.Color(94, 42, 43));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab3MouseEntered(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(201, 169, 154));
        jLabel6.setText("   Atividades");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab3Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel1.add(tab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 140, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/SIGBlogo200x200.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 190, 110));

        SairLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Exit50x85.png"))); // NOI18N
        SairLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SairLabelMouseEntered(evt);
            }
        });
        jPanel1.add(SairLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 141, 470));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(94, 42, 43));

        txtPesquisar.setBackground(new java.awt.Color(94, 42, 43));
        txtPesquisar.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txtPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisar.setText("Pesquisar...");
        txtPesquisar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(201, 169, 154)));
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        lupaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Lupa35x35.png"))); // NOI18N
        lupaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lupaLabelMouseEntered(evt);
            }
        });
        lupaLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lupaLabelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lupaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lupaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jP01.setBackground(new java.awt.Color(255, 255, 255));
        jP01.setLayout(new java.awt.CardLayout());

        BibliotecaPanel.setBackground(new java.awt.Color(255, 255, 255));
        BibliotecaPanel.setMaximumSize(new java.awt.Dimension(0, 0));
        BibliotecaPanel.setPreferredSize(new java.awt.Dimension(770, 406));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        BibliotecaTable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BibliotecaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID", "Genero", "Tilulo", "Autor", "Disponiveis" }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Tabela não editável
            }
        });
        jScrollPane1.setViewportView(BibliotecaTable);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new java.awt.Color(201, 169, 154));
        headerRenderer.setForeground(new java.awt.Color(94,42,43));
        headerRenderer.setFont(new java.awt.Font("Times New Roman", java.awt.Font.ITALIC, 14));

        // Aplica em todas as colunas do cabeçalho
        for (int i = 0; i < BibliotecaTable.getColumnModel().getColumnCount(); i++) {
            BibliotecaTable.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }

        txtLivroTaxa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtLivroTaxa.setText("0.00 MZN");
        txtLivroTaxa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLivroTaxaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLivroTaxaFocusLost(evt);
            }
        });
        txtLivroTaxa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLivroTaxaActionPerformed(evt);
            }
        });
        txtLivroTaxa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLivroTaxaKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Taxa unica dos Livros ");

        javax.swing.GroupLayout BibliotecaPanelLayout = new javax.swing.GroupLayout(BibliotecaPanel);
        BibliotecaPanel.setLayout(BibliotecaPanelLayout);
        BibliotecaPanelLayout.setHorizontalGroup(
            BibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BibliotecaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BibliotecaPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BibliotecaPanelLayout.createSequentialGroup()
                        .addComponent(txtLivroTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(73, 73, 73))))
        );
        BibliotecaPanelLayout.setVerticalGroup(
            BibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BibliotecaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BibliotecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLivroTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jP01.add(BibliotecaPanel, "card2");

        CadastrarLivrosPanel.setBackground(new java.awt.Color(255, 255, 255));
        CadastrarLivrosPanel.setPreferredSize(new java.awt.Dimension(770, 406));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(94, 42, 43));
        jLabel9.setText("Autor:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(94, 42, 43));
        jLabel12.setText("Gênero:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(94, 42, 43));
        jLabel14.setText("Titulo:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(94, 42, 43));
        jLabel15.setText("Quantidade:");

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 42, 43)));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });

        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 42, 43)));
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });

        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 42, 43)));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jSpinner1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));

        jButton2.setBackground(new java.awt.Color(94, 42, 43));
        jButton2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Concluido");
        //jButton2.setBorder(BorderFactory.createLineBorder(new Color(201, 169, 154), 2, true));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/SIGBlogo300x300.png"))); // NOI18N

        javax.swing.GroupLayout CadastrarLivrosPanelLayout = new javax.swing.GroupLayout(CadastrarLivrosPanel);
        CadastrarLivrosPanel.setLayout(CadastrarLivrosPanelLayout);
        CadastrarLivrosPanelLayout.setHorizontalGroup(
            CadastrarLivrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarLivrosPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(CadastrarLivrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CadastrarLivrosPanelLayout.createSequentialGroup()
                        .addGroup(CadastrarLivrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastrarLivrosPanelLayout.createSequentialGroup()
                                .addGroup(CadastrarLivrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(CadastrarLivrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CadastrarLivrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                        .addComponent(jTextField5))
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CadastrarLivrosPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(31, 31, 31)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        CadastrarLivrosPanelLayout.setVerticalGroup(
            CadastrarLivrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarLivrosPanelLayout.createSequentialGroup()
                .addGroup(CadastrarLivrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastrarLivrosPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(CadastrarLivrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CadastrarLivrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CadastrarLivrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CadastrarLivrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CadastrarLivrosPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jP01.add(CadastrarLivrosPanel, "card3");

        AtividadeGestPanel.setBackground(new java.awt.Color(255, 255, 255));
        AtividadeGestPanel.setPreferredSize(new java.awt.Dimension(770, 406));

        jTable4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Data de solicitação", "Nome", "Livro ID", "Valor", "Multa"}
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Tabela não editável
            }
        });
        jScrollPane5.setViewportView(jTable4);
        DefaultTableCellRenderer headerRenderer4 = new DefaultTableCellRenderer();
        headerRenderer4.setBackground(new java.awt.Color(201, 169, 154));
        headerRenderer4.setForeground(new java.awt.Color(94,42,43));
        headerRenderer4.setFont(new java.awt.Font("Times New Roman", java.awt.Font.ITALIC, 14));

        // Aplica em todas as colunas do cabeçalho
        for (int i = 0; i < jTable4.getColumnModel().getColumnCount(); i++) {
            jTable4.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer4);
        }

        jButton5.setBackground(new java.awt.Color(94, 42, 43));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Imprimir Relatório");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(94, 42, 43));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Atualizar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AtividadeGestPanelLayout = new javax.swing.GroupLayout(AtividadeGestPanel);
        AtividadeGestPanel.setLayout(AtividadeGestPanelLayout);
        AtividadeGestPanelLayout.setHorizontalGroup(
            AtividadeGestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtividadeGestPanelLayout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AtividadeGestPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(45, 45, 45))
        );
        AtividadeGestPanelLayout.setVerticalGroup(
            AtividadeGestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtividadeGestPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AtividadeGestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jP01.add(AtividadeGestPanel, "card4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP01, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP01, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 780, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        // BiliotecaPanel
        BibliotecaPanel.setVisible(true);
        CadastrarLivrosPanel.setVisible(false);
        AtividadeGestPanel.setVisible(false);
        
        tab1.setBackground(Color.white);
        tab2.setBackground(new Color(94,42,43));
        tab3.setBackground(new Color(94,42,43));
    }//GEN-LAST:event_tab1MouseClicked

    private void tab1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseEntered
        // TODO add your handling code here:
        tab1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_tab1MouseEntered

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        // Cadastrar Livros Panel
        CadastrarLivrosPanel.setVisible(true);
        BibliotecaPanel.setVisible(false);
        AtividadeGestPanel.setVisible(false);

        tab2.setBackground(Color.white);
        tab1.setBackground(new Color(94,42,43));
        tab3.setBackground(new Color(94,42,43));
    }//GEN-LAST:event_tab2MouseClicked

    private void tab2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseEntered
        // TODO add your handling code here:
        tab2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_tab2MouseEntered

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        // AtidadePanel
        AtividadeGestPanel.setVisible(true);
        CadastrarLivrosPanel.setVisible(false);
        BibliotecaPanel.setVisible(false);

        tab3.setBackground(Color.white);
        tab2.setBackground(new Color(94,42,43));
        tab1.setBackground(new Color(94,42,43));
    }//GEN-LAST:event_tab3MouseClicked

    private void tab3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseEntered
        // TODO add your handling code here:
        tab3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_tab3MouseEntered

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:

        //String termo = txtPesquisar.getText().trim().toLowerCase();

        // Exemplo de lógica de pesquisa
        /* if (painelLivros.isVisible()) {
            pesquisarLivros(termo);
        } else if (painelClientes.isVisible()) {
            pesquisarClientes(termo);
        } else if (painelEmprestimos.isVisible()) {
            pesquisarEmprestimos(termo);
        }
        }*/
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void lupaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaLabelMouseClicked
        // Metodo de pesquisa para aqui tambem
    
     String termo = txtPesquisar.getText().toLowerCase().trim();
    
    if (termo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Digite algo para pesquisar!");
        return;
    }
    
    if (BibliotecaPanel.isVisible()) {
        // Pesquisar livros
        DefaultTableModel model = (DefaultTableModel) BibliotecaTable.getModel();
        model.setRowCount(0);
        
        boolean encontrou = false;
        
        for (Livros livro : (List<Livros>) livroDAO.listarLivros()) {
            if (livro.getTitulo().toLowerCase().contains(termo) ||
                livro.getAutor().toLowerCase().contains(termo) ||
                livro.getGenero().toLowerCase().contains(termo) ||
                String.valueOf(livro.getIdLivro()).contains(termo)) { // ✅ getIdLivro()
                
                model.addRow(new Object[]{
                    livro.getIdLivro(), 
                    livro.getGenero(), 
                    livro.getTitulo(), 
                    livro.getAutor(), 
                    livro.getNumLivros()
                });
                encontrou = true;
            }
        }
        
        if (!encontrou) {
            JOptionPane.showMessageDialog(this, "Nenhum livro encontrado com: " + termo);
        }
    
        
    } else if (AtividadeGestPanel.isVisible()) {
    // Pesquisar emprestimos
    DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
    model.setRowCount(0);
    
    boolean encontrou = false;
    for (Emprestimos emp : emprestimoDAO.listarEmprestimos()) {
        if (emp.getNome().toLowerCase().contains(termo) ||
            String.valueOf(emp.getValor()).contains(termo) ||
            String.valueOf(emp.getLivroId()).contains(termo)) { //  pesquisar por ID do livro
            
            double multa = emprestimoDAO.calcularMulta(emp);
            model.addRow(new Object[]{
                emp.getDataLimite().minusDays(7).format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                emp.getNome(),
                "LIVRO-" + emp.getLivroId(), 
                emp.getValor() + " MZN",
                multa > 0 ? multa + " MZN" : "Sem multa"
            });
            encontrou = true;
        }
    }
}

    }//GEN-LAST:event_lupaLabelMouseClicked

    private void lupaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaLabelMouseEntered
        // TODO add your handling code here:
        lupaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lupaLabelMouseEntered

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
     //  "Imprimir Relatorio" 

    int totalLivros = ((List<Livros>) livroDAO.listarLivros()).size();
    int totalEmprestimos = ((List<Emprestimos>) emprestimoDAO.listarEmprestimos()).size();
    double totalMultas = 0;
    
    // Calcular total de multas
    for (Emprestimos emp : (List<Emprestimos>) emprestimoDAO.listarEmprestimos()) {
        totalMultas += emprestimoDAO.calcularMulta(emp);
    }
    
     JTextArea textoRelatorio = new JTextArea();
    textoRelatorio.setEditable(false);
    textoRelatorio.setFont(new Font("Monospaced", Font.BOLD, 12));
    
    String relatorio = "===== RELATÓRIO DE ATIVIDADES =====\n" +
                      "Data: " + java.time.LocalDate.now() + "\n" +
                      "Total de livros cadastrados: " + totalLivros + "\n" +
                      "Total de empréstimos: " + totalEmprestimos + "\n" +
                      "Taxa atual por livro: " + taxaEmprestimo + " MZN\n" +
                      "Total em multas: " + totalMultas + " MZN\n" +
                      "Receita total: " + (totalEmprestimos * taxaEmprestimo) + " MZN\n" +
                      "Total geral: " + ( (totalMultas + (totalEmprestimos * taxaEmprestimo))) + " MZN\n\n" +
                      "-------------------------------------------------\n"+
                       "Sistema SIGB - Relatório de Atividade";
                 textoRelatorio.setText(relatorio);
    
    // Diálogo de confirmação antes de imprimir
    int option = JOptionPane.showConfirmDialog(this, 
        "Deseja imprimir o relatório de Atividades?",
        "Confirmar Impressão", 
        JOptionPane.YES_NO_OPTION);
    
    if (option == JOptionPane.YES_OPTION) {
        try {
            // Executar impressão real
            boolean printed = textoRelatorio.print();
            
            if (printed) {
                JOptionPane.showMessageDialog(this, 
                    "Relatório enviado para impressão com sucesso!",
                    "Impressão Concluída", 
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Impressão cancelada pelo usuário",
                    "Impressão Cancelada", 
                    JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (java.awt.print.PrinterException e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao imprimir: " + e.getMessage(),
                "Erro de Impressão", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
     
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtLivroTaxaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLivroTaxaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLivroTaxaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    String autor = jTextField6.getText().trim();
    String genero = jTextField5.getText().trim();
    String titulo = jTextField7.getText().trim();
    int quantidade = (Integer) jSpinner1.getValue();
    
    // Validacao
    if (autor.isEmpty() || genero.isEmpty() || titulo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        // Gerar ID unico
        int novoId = ((List<Livros>) livroDAO.listarLivros()).size() + 1;
        
      
        Livros novoLivro = new Livros(
            novoId,           // idLivro
            autor,            // autor
            genero,           // genero
            titulo,           // titulo
            quantidade,       // numLivros
            true,             // status (disponivel)
            0.0               // valorLivro 
        );
        
        livroDAO.salvarLivro(novoLivro);
        
        RegistroAtividade.registrarCadastroLivro(
       this.nomeUsuario, // Nome do gestor
        "Gestor",       // Funcao
        titulo,         // Título do livro
        autor,          // Autor do livro
        quantidade      // Quantidade
        );
        
        JOptionPane.showMessageDialog(this, 
            "Livro cadastrado com sucesso!\n" +
            "ID: " + novoId + "\n" +
            "Título: " + titulo, 
            "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        
        limparCamposCadastro();
        carregarTabelaLivros();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar livro: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton2ActionPerformed
private void limparCamposCadastro() {
    jTextField6.setText("");
    jTextField5.setText("");
    jTextField7.setText("");
    jSpinner1.setValue(1);
}
    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         carregarAtividadesGestor();
    JOptionPane.showMessageDialog(this, 
        "Atividades atualizadas!\n" +
        "Multas verificadas automaticamente.", 
        "Atualizado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        // TODO add your handling code here:
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton5MouseEntered

    private void txtLivroTaxaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLivroTaxaFocusGained
        // TODO add your handling code here:
     if (txtLivroTaxa.getText().endsWith(" MZN")) {
        txtLivroTaxa.setText(String.valueOf(taxaEmprestimo));
    }

    }//GEN-LAST:event_txtLivroTaxaFocusGained

    private void txtLivroTaxaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLivroTaxaFocusLost
        // TODO add your handling code here:
      // METODO PARA DEFINIR TAXA
    try {
        // Remover "MZN" se existir
        String texto = txtLivroTaxa.getText().replace("MZN", "").trim();
        
        if (!texto.isEmpty()) {
            double taxaAntiga = taxaEmprestimo;
            double novaTaxa = Double.parseDouble(texto);
            
            
            if (novaTaxa <= 0) {
                JOptionPane.showMessageDialog(this, "A taxa deve ser maior que zero!", "Erro", JOptionPane.ERROR_MESSAGE);
                txtLivroTaxa.setText(taxaEmprestimo + " MZN");
                return;
            }
            
            // SALVAR NOVA TAXA
            taxaEmprestimo = novaTaxa;
            configDAO.salvarTaxaEmprestimo(taxaEmprestimo);
            
             // Registrar a atividade de alteracao de taxa
            RegistroAtividade.registrarAlteracaoTaxa(
                this.nomeUsuario, // Nome do gestor
                "Gestor",       // Funcao
                taxaAntiga,     // Taxa anterior
                novaTaxa        // Nova taxa
            );
            
            txtLivroTaxa.setText(taxaEmprestimo + " MZN");
            JOptionPane.showMessageDialog(this, 
                "Taxa de empréstimo atualizada!\n" +
                "Nova taxa: " + taxaEmprestimo + " MZN por livro\n" +
                "Esta taxa será aplicada em todos os novos empréstimos.", 
                "Taxa Atualizada", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Digite um valor válido para a taxa!", "Erro", JOptionPane.ERROR_MESSAGE);
        txtLivroTaxa.setText(taxaEmprestimo + " MZN");
    }


    }//GEN-LAST:event_txtLivroTaxaFocusLost

    private void txtLivroTaxaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLivroTaxaKeyPressed
        // TODO add your handling code here:
          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        txtLivroTaxaFocusLost(null);
    
    }
    }//GEN-LAST:event_txtLivroTaxaKeyPressed

    private void lupaLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lupaLabelKeyPressed
        // TODO add your handling code here:
       


    }//GEN-LAST:event_lupaLabelKeyPressed
                 // Pesquisa com Enter
    private void txtPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyPressed
        // TODO add your handling code here:
       
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        lupaLabelMouseClicked(null);
    }
  

    }//GEN-LAST:event_txtPesquisarKeyPressed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        // TODO add your handling code here:
     
// Pesquisa em tempo real
    String termo = txtPesquisar.getText().toLowerCase();
    
    if (BibliotecaPanel.isVisible()) {
        DefaultTableModel model = (DefaultTableModel) BibliotecaTable.getModel();
        model.setRowCount(0);
        
        
        for (Livros livro : (List<Livros>) this.livroDAO.listarLivros()) {
                
                model.addRow(new Object[]{
                    livro.getIdLivro(), 
                    livro.getGenero(), 
                    livro.getTitulo(), 
                    livro.getAutor(), 
                    livro.getNumLivros()
                });
            }
        }
    


    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void SairLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairLabelMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
            "Deseja sair do sistema?", "Confirmar Saída",
            JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_SairLabelMouseClicked

    private void SairLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairLabelMouseEntered
        // TODO add your handling code here:
        SairLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_SairLabelMouseEntered

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jTextField5.requestFocus(); // Vai para o campo de genero
    }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jTextField7.requestFocus(); // Vai para o campo de titulo
    }
    }//GEN-LAST:event_jTextField5KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuGestor().setVisible(true));
    }

    //METODOS
         // Tabela de livros
    private void carregarTabelaLivros() {
    DefaultTableModel model = (DefaultTableModel) BibliotecaTable.getModel();
    model.setRowCount(0);
    
    try {
        
        if (this.livroDAO == null) {
            this.livroDAO = new DAO.LivrosDAO();
        }
        
        
        var livros = (java.util.List<model.Livros>) this.livroDAO.listarLivros();
        
        for (var livro : livros) {
            model.addRow(new Object[]{
                livro.getIdLivro(),
                livro.getGenero(),
                livro.getTitulo(),
                livro.getAutor(),
                livro.getNumLivros()
            });
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar livros: " + e.getMessage());
    }
    }
    
    // Carregar atividades
    private void carregarAtividadesGestor() {
     DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
    model.setRowCount(0);
    
    try {
       
        EmprestimosDAO empDAO = new EmprestimosDAO();
        List<Emprestimos> emprestimos = (List<Emprestimos>) empDAO.listarEmprestimos();
        
        for (Emprestimos emp : emprestimos) {
            double multa = empDAO.calcularMulta(emp);
            
            model.addRow(new Object[]{
            emp.getDataLimite().minusDays(7).format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy")),
            emp.getNome(),
            "LIVRO-" + emp.getLivroId(), // ← CORREÇÃO: usar getLivroId() em vez de hashCode()
            emp.getValor() + " MZN",
            multa > 0 ? multa + " MZN" : "Sem multa"
       });
            
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar atividades: " + e.getMessage());
        e.printStackTrace();
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AtividadeGestPanel;
    private javax.swing.JPanel BibliotecaPanel;
    private javax.swing.JTable BibliotecaTable;
    private javax.swing.JPanel CadastrarLivrosPanel;
    private javax.swing.JLabel SairLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jP01;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lupaLabel;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JTextField txtLivroTaxa;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

}